### ISSUE TITLE
what am i doing wrong

### ISSUE THREAD

**Issue by weit8** [makeuseofcode/React_DALL-E_API#2]
so i got it ot load a page saying generate an image using open ai 

but no images will generate on the page

**Comment by weit8** [comment]
i solved the main problem but is there a way to pick the resolution like 1920x1080 and not just a square? or even make 4 or move photos at once

**Comment by ItsWachira** [comment]
Check out the official [DALL-E API Docs](https://platform.openai.com/docs/guides/images) for clarifications on how you can customize the size of the generated Images. For the number of images, You can request 1-10 images at a time using the [n] parameter passed in the **create** function.

**Comment by weit8** [comment]
Thank you so much
